spring:
  application:
    name: shopAgent
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  h2:
    console:
      enabled: true
      path: /h2-console

  logging:
    level:
      org.hibernate.SQL: info
custom:
  h2:
    url: jdbc:h2:file:./data/shopagent-h2-db
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    root: info
    org.mybatis: debug
    org.apache.ibatis: debug
    java.sql: debug
    jdbc: debug
    com.zaxxer.hikari: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true